// users endpoints
#######
POST http://localhost:8080/users/login
Content-Type: application/json


{
    "uemail": "githaigageorge12@gmail.com",
    "upassword": "@krakenJO32?"
}


#########
GET http://localhost:8080/email/reseted?uzeremail='githaigageorge12@gmail.com'

######
POST http://localhost:8080/users
Content-Type: application/json


{
    "uname": "Jack Sparrow",
    "uemail": "jacckyRow@gmail.com",
    "upassword": "@krakenJO32?",
    "confirmpassword": "@krakenJO32?"
}


#####
GET http://localhost:8080/users
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI4YzEzMmM0ZS1iMjM4LTQ4MWMtOWViNS0yNmM4ZDU3OGQ3NTEiLCJ1bmFtZSI6IkpvaGhueSBEZWVwIiwidWVtYWlsIjoiZ2l0aGFpZ2FnZW9yZ2UxMkBnbWFpbC5jb20iLCJ1cm9sZSI6ImFkbWluIiwiaWF0IjoxNjg3OTgwNTg3LCJleHAiOjE2ODgwMDkzODd9.H4BoaDCf81HK5Nhd2VRQyII3OWPWdGdeV6pAhfkoZDM

#####
GET http://localhost:8080/users/id/8c132c4e-b238-481c-9eb5-26c8d578d751
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxZGMyZWMxYi1mMWZkLTQ2ZjQtOThhYi1hMTZhNjcyMGZkNzUiLCJ1bmFtZSI6IkNwdCBCYXJib3NhIiwidWVtYWlsIjoiY2FyaWJlYW40QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4NzUxNzQ5NCwiZXhwIjoxNjg3NTE3NDk2fQ.Pdiq5UWkopq1fk1f2YA50ET1kV9s-m0-UIN-2_XJLVw



####
GET  http://localhost:8080/users/barittos?uzeremail='barca10@gmail.com'
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI4YzEzMmM0ZS1iMjM4LTQ4MWMtOWViNS0yNmM4ZDU3OGQ3NTEiLCJ1bmFtZSI6IkpvaGhueSBEZWVwIiwidWVtYWlsIjoiZ2l0aGFpZ2FnZW9yZ2UxMkBnbWFpbC5jb20iLCJ1cm9sZSI6ImFkbWluIiwiaWF0IjoxNjg4MDI0Nzk0LCJleHAiOjE2ODgwNTM1OTR9.I6o7iQiOPQIWteK8oSvgytHNuXbRzzoLvLEzYVUpj-A


#####
PUT http://localhost:8080/users/03d1c15f-f058-4393-a49e-090af0c955b2
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJjMTE0YjlmYS0wYzFiLTQ0YzMtODgxMS0yNDYyZjExNTgwMzAiLCJ1bmFtZSI6IlNlbmlvciBEZXYiLCJ1ZW1haWwiOiJzZW5pb3JkZXZAZ21haWwuY29tIiwidXJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg4MDQ1Nzc4LCJleHAiOjE2ODgwNzQ1Nzh9.YG-N4g84kb1XG6iKT2nle4gaOMAeJ44Z3Lowx609B90

{    
    "uname": "Smart Farmer",
    "uemail": "smartFarmer@gmail.com",
    "upassword": "@krakenJO32?",
    "urole": "admin",
    "uprofPic": "personavatar.jpg"
    
}


######
DELETE http://localhost:8080/users/barca10@gmail.com
token: eyJzMmM0ZS1iMjM4LTQ4MWMtOWViNS0yNmM4ZDU3OGQ3NTEiLCJ1bmFtZSI6IkpvaGhueSBEZWVwIiwidWVtYWlsIjoiZ2l0aGFpZ2FnZW9yZ2UxMkBnbWFpbC5jb20iLCJ1cm9sZSI6ImFkbWluIiwiaWF0IjoxNjg3NDI1MDc3LCJleHAiOjE2ODc0Mjg2Nzd9.Sfcva4heua02S_yl6qiGgeUXiU27HzK3NNZpnWFleR0



/// questions endpoints
######
POST http://localhost:8080/questions
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI4NjAyOTE1NS1iYmFiLTQ2N2YtOTc0Mi1lZDEzNDQ2MjkyMzYiLCJ1bmFtZSI6IkpvbmVzIiwidWVtYWlsIjoiY2FyaWJlYW41QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4Nzg3NzcxNSwiZXhwIjoxNjg3OTA2NTE1fQ.pmYewsavyG4XygIL4TsRyXX797K0SzTPT8LMwIJSwWM

{
    
    "qtitle": "this is a simple question again",
    "qbody": "<p>&lt;p&gt;the questions is not as simple as it is because of many becauses&lt;/p&gt;</p>",
    "tname": ""
}


#####
GET http://localhost:8080/questions
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI4YzEzMmM0ZS1iMjM4LTQ4MWMtOWViNS0yNmM4ZDU3OGQ3NTEiLCJ1bmFtZSI6IkpvaGhueSBEZWVwIiwidWVtYWlsIjoiZ2l0aGFpZ2FnZW9yZ2UxMkBnbWFpbC5jb20iLCJ1cm9sZSI6ImFkbWluIiwiaWF0IjoxNjg3OTgwNTg3LCJleHAiOjE2ODgwMDkzODd9.H4BoaDCf81HK5Nhd2VRQyII3OWPWdGdeV6pAhfkoZDM



#####
GET http://localhost:8080/questions/qq34
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxZGMyZWMxYi1mMWZkLTQ2ZjQtOThhYi1hMTZhNjcyMGZkNzUiLCJ1bmFtZSI6IkNwdCBCYXJib3NhIiwidWVtYWlsIjoiY2FyaWJlYW40QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4NzQyODUyNCwiZXhwIjoxNjg3NDMyMTI0fQ.mAitK4e2bZlGAWLhMQnn8fSxNS87kSkMMLORlhobluU




#####
GET http://localhost:8080/questions/email/samuelndambuki401@gmail.com
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxZGMyZWMxYi1mMWZkLTQ2ZjQtOThhYi1hMTZhNjcyMGZkNzUiLCJ1bmFtZSI6IkNwdCBCYXJib3NhIiwidWVtYWlsIjoiY2FyaWJlYW40QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4NzQyODUyNCwiZXhwIjoxNjg3NDMyMTI0fQ.mAitK4e2bZlGAWLhMQnn8fSxNS87kSkMMLORlhobluU



#####
PUT http://localhost:8080/questions/qq32
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxZGMyZWMxYi1mMWZkLTQ2ZjQtOThhYi1hMTZhNjcyMGZkNzUiLCJ1bmFtZSI6IkNwdCBCYXJib3NhIiwidWVtYWlsIjoiY2FyaWJlYW40QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4NzQyODUyNCwiZXhwIjoxNjg3NDMyMTI0fQ.mAitK4e2bZlGAWLhMQnn8fSxNS87kSkMMLORlhobluU


{
    "qtitle": "How do i go to nanyuki",
    "qbody": "am currently in Mweiga and i need to go to Nanyuki"
}


#####
DELETE http://localhost:8080/questions/8da2a501-9a38-4601-bbbd-2356650b5707
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI4YzEzMmM0ZS1iMjM4LTQ4MWMtOWViNS0yNmM4ZDU3OGQ3NTEiLCJ1bmFtZSI6IkpvaGhueSBEZWVwIiwidWVtYWlsIjoiZ2l0aGFpZ2FnZW9yZ2UxMkBnbWFpbC5jb20iLCJ1cm9sZSI6ImFkbWluIiwiaWF0IjoxNjg3NDI1MDc3LCJleHAiOjE2ODc0Mjg2Nzd9.Sfcva4heua02S_yl6qiGgeUXiU27HzK3NNZpnWFleR0



/// answer endpoints
######
POST http://localhost:8080/answers
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxZGMyZWMxYi1mMWZkLTQ2ZjQtOThhYi1hMTZhNjcyMGZkNzUiLCJ1bmFtZSI6IkNwdCBCYXJib3NhIiwidWVtYWlsIjoiY2FyaWJlYW40QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4NzQyODUyNCwiZXhwIjoxNjg3NDMyMTI0fQ.mAitK4e2bZlGAWLhMQnn8fSxNS87kSkMMLORlhobluU



{
    "qid": "31219baa-2b90-4ab5-bdc9-10b50114c90b",
    "atitle": "y",
    "abody": "Since there are various matatus U should choose 2NK"
}


######
GET http://localhost:8080/answers
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxZGMyZWMxYi1mMWZkLTQ2ZjQtOThhYi1hMTZhNjcyMGZkNzUiLCJ1bmFtZSI6IkNwdCBCYXJib3NhIiwidWVtYWlsIjoiY2FyaWJlYW40QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4NzQyODUyNCwiZXhwIjoxNjg3NDMyMTI0fQ.mAitK4e2bZlGAWLhMQnn8fSxNS87kSkMMLORlhobluU



######
GET http://localhost:8080/answers/aid/ksds223
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxZGMyZWMxYi1mMWZkLTQ2ZjQtOThhYi1hMTZhNjcyMGZkNzUiLCJ1bmFtZSI6IkNwdCBCYXJib3NhIiwidWVtYWlsIjoiY2FyaWJlYW40QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4NzQyODUyNCwiZXhwIjoxNjg3NDMyMTI0fQ.mAitK4e2bZlGAWLhMQnn8fSxNS87kSkMMLORlhobluU


#####
GET http://localhost:8080/answers/qid/qq32
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxZGMyZWMxYi1mMWZkLTQ2ZjQtOThhYi1hMTZhNjcyMGZkNzUiLCJ1bmFtZSI6IkNwdCBCYXJib3NhIiwidWVtYWlsIjoiY2FyaWJlYW40QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4NzQyODUyNCwiZXhwIjoxNjg3NDMyMTI0fQ.mAitK4e2bZlGAWLhMQnn8fSxNS87kSkMMLORlhobluU



#####
PUT http://localhost:8080/answers/ksds223
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxZGMyZWMxYi1mMWZkLTQ2ZjQtOThhYi1hMTZhNjcyMGZkNzUiLCJ1bmFtZSI6IkNwdCBCYXJib3NhIiwidWVtYWlsIjoiY2FyaWJlYW40QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4NzQyODUyNCwiZXhwIjoxNjg3NDMyMTI0fQ.mAitK4e2bZlGAWLhMQnn8fSxNS87kSkMMLORlhobluU


{
    "atitle": "Go to Nyeri town and book a matatu",
    "abody": "Since there are various matatus U should choose 2NK"
}



// tag endpoints
######
POST http://localhost:8080/tags
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI4NjAyOTE1NS1iYmFiLTQ2N2YtOTc0Mi1lZDEzNDQ2MjkyMzYiLCJ1bmFtZSI6IkpvbmVzIiwidWVtYWlsIjoiY2FyaWJlYW41QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4Nzc4Nzc2NywiZXhwIjoxNjg3ODE2NTY3fQ.U-MxWJ2aF9uWIq0_OVryTdA5HTt2RLZqZx7GWAgcmQo


{
    "tname": ["motor-cycling","adventures"]
}


####
GET http://localhost:8080/tags
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI4NjAyOTE1NS1iYmFiLTQ2N2YtOTc0Mi1lZDEzNDQ2MjkyMzYiLCJ1bmFtZSI6IkpvbmVzIiwidWVtYWlsIjoiY2FyaWJlYW41QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4Nzc4Nzc2NywiZXhwIjoxNjg3ODE2NTY3fQ.U-MxWJ2aF9uWIq0_OVryTdA5HTt2RLZqZx7GWAgcmQo

####
GET http://localhost:8080/tags/0b3a91ae-3cfe-4e37-9eef-860d84e5501a
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI4NjAyOTE1NS1iYmFiLTQ2N2YtOTc0Mi1lZDEzNDQ2MjkyMzYiLCJ1bmFtZSI6IkpvbmVzIiwidWVtYWlsIjoiY2FyaWJlYW41QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4Nzc4Nzc2NywiZXhwIjoxNjg3ODE2NTY3fQ.U-MxWJ2aF9uWIq0_OVryTdA5HTt2RLZqZx7GWAgcmQo

######
GET http://localhost:8080/tags/qid/74d75ed0-7bb1-45e6-ad10-8e13841a588e
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI4NjAyOTE1NS1iYmFiLTQ2N2YtOTc0Mi1lZDEzNDQ2MjkyMzYiLCJ1bmFtZSI6IkpvbmVzIiwidWVtYWlsIjoiY2FyaWJlYW41QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4Nzg3NzcxNSwiZXhwIjoxNjg3OTA2NTE1fQ.pmYewsavyG4XygIL4TsRyXX797K0SzTPT8LMwIJSwWM



/// comments endpoints
####
POST http://localhost:8080/comments
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI4YzEzMmM0ZS1iMjM4LTQ4MWMtOWViNS0yNmM4ZDU3OGQ3NTEiLCJ1bmFtZSI6IkpvaGhueSBEZWVwIiwidWVtYWlsIjoiZ2l0aGFpZ2FnZW9yZ2UxMkBnbWFpbC5jb20iLCJ1cm9sZSI6ImFkbWluIiwiaWF0IjoxNjg3OTQ4NjU2LCJleHAiOjE2ODc5Nzc0NTZ9.fOO40U1ucX80Zn0U772dwIxJ4YBhPnVOFfk1Ays_m0w



{
    "aid": "19cca528-5dbc-4765-93ed-a4ae0f68a8f4",
    "cbody": "2NK are expensive"
}


#####
GET http://localhost:8080/comments


####
GET http://localhost:8080/comments/aid/19cca528-5dbc-4765-93ed-a4ae0f68a8f4
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxZGMyZWMxYi1mMWZkLTQ2ZjQtOThhYi1hMTZhNjcyMGZkNzUiLCJ1bmFtZSI6IkNwdCBCYXJib3NhIiwidWVtYWlsIjoiY2FyaWJlYW40QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4NzQyODUyNCwiZXhwIjoxNjg3NDMyMTI0fQ.mAitK4e2bZlGAWLhMQnn8fSxNS87kSkMMLORlhobluU


#####
GET http://localhost:8080/comments/cid/1d9f7af2-e485-4b16-a60c-2e2404461fb9
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxZGMyZWMxYi1mMWZkLTQ2ZjQtOThhYi1hMTZhNjcyMGZkNzUiLCJ1bmFtZSI6IkNwdCBCYXJib3NhIiwidWVtYWlsIjoiY2FyaWJlYW40QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4NzQyODUyNCwiZXhwIjoxNjg3NDMyMTI0fQ.mAitK4e2bZlGAWLhMQnn8fSxNS87kSkMMLORlhobluU


#####
PUT http://localhost:8080/comments/1d9f7af2-e485-4b16-a60c-2e2404461fb9
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxZGMyZWMxYi1mMWZkLTQ2ZjQtOThhYi1hMTZhNjcyMGZkNzUiLCJ1bmFtZSI6IkNwdCBCYXJib3NhIiwidWVtYWlsIjoiY2FyaWJlYW40QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4NzQyODUyNCwiZXhwIjoxNjg3NDMyMTI0fQ.mAitK4e2bZlGAWLhMQnn8fSxNS87kSkMMLORlhobluU


{

     "cbody": "2NK are expensive, consider 4NTE"
}



#####
POST http://localhost:8080/answer-votes
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxZGMyZWMxYi1mMWZkLTQ2ZjQtOThhYi1hMTZhNjcyMGZkNzUiLCJ1bmFtZSI6IkNwdCBCYXJib3NhIiwidWVtYWlsIjoiY2FyaWJlYW40QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4NzQyODUyNCwiZXhwIjoxNjg3NDMyMTI0fQ.mAitK4e2bZlGAWLhMQnn8fSxNS87kSkMMLORlhobluU



{
    "aid": "",
    "aupvotes": 5, 
    "adownvotes": 2,
    "apreffered": 1
}


#####
GET http://localhost:8080/answer-votes
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxZGMyZWMxYi1mMWZkLTQ2ZjQtOThhYi1hMTZhNjcyMGZkNzUiLCJ1bmFtZSI6IkNwdCBCYXJib3NhIiwidWVtYWlsIjoiY2FyaWJlYW40QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4NzQyODUyNCwiZXhwIjoxNjg3NDMyMTI0fQ.mAitK4e2bZlGAWLhMQnn8fSxNS87kSkMMLORlhobluU



#####
GET http://localhost:8080/answer-votes/aid/aakds223
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxZGMyZWMxYi1mMWZkLTQ2ZjQtOThhYi1hMTZhNjcyMGZkNzUiLCJ1bmFtZSI6IkNwdCBCYXJib3NhIiwidWVtYWlsIjoiY2FyaWJlYW40QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4NzQyODUyNCwiZXhwIjoxNjg3NDMyMTI0fQ.mAitK4e2bZlGAWLhMQnn8fSxNS87kSkMMLORlhobluU


#####
GET http://localhost:8080/answer-votes/avid/c3f190df-3485-4315-9d82-f5fd88f8e1b6
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxZGMyZWMxYi1mMWZkLTQ2ZjQtOThhYi1hMTZhNjcyMGZkNzUiLCJ1bmFtZSI6IkNwdCBCYXJib3NhIiwidWVtYWlsIjoiY2FyaWJlYW40QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4NzQyODUyNCwiZXhwIjoxNjg3NDMyMTI0fQ.mAitK4e2bZlGAWLhMQnn8fSxNS87kSkMMLORlhobluU


#####
PUT http://localhost:8080/answer-votes/c3f190df-3485-4315-9d82-f5fd88f8e1b6
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxZGMyZWMxYi1mMWZkLTQ2ZjQtOThhYi1hMTZhNjcyMGZkNzUiLCJ1bmFtZSI6IkNwdCBCYXJib3NhIiwidWVtYWlsIjoiY2FyaWJlYW40QGdtYWlsLmNvbSIsInVyb2xlIjoidXNlciIsImlhdCI6MTY4NzQyODUyNCwiZXhwIjoxNjg3NDMyMTI0fQ.mAitK4e2bZlGAWLhMQnn8fSxNS87kSkMMLORlhobluU


{
    "aid": "",
    "aupvotes": 5, 
    "adownvotes": 2,
    "apreffered": 1
}

######
PUT http://localhost:8080/tags
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI4YzEzMmM0ZS1iMjM4LTQ4MWMtOWViNS0yNmM4ZDU3OGQ3NTEiLCJ1bmFtZSI6IkpvaGhueSBEZWVwIiwidWVtYWlsIjoiZ2l0aGFpZ2FnZW9yZ2UxMkBnbWFpbC5jb20iLCJ1cm9sZSI6ImFkbWluIiwiaWF0IjoxNjg4MDI0Nzk0LCJleHAiOjE2ODgwNTM1OTR9.I6o7iQiOPQIWteK8oSvgytHNuXbRzzoLvLEzYVUpj-A


{
    "qid":"077d2c39-5c79-466a-bb2e-f7c5bbfba0a8",
    "tid":"5addb2f4-b4be-4b88-aee9-325190f8d2a4",
    "tname": "afternext"

}


#########
DELETE http://localhost:8080/tags/b34d98dd-4e14-4348-a41c-2364ad568f77
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI4YzEzMmM0ZS1iMjM4LTQ4MWMtOWViNS0yNmM4ZDU3OGQ3NTEiLCJ1bmFtZSI6IkpvaGhueSBEZWVwIiwidWVtYWlsIjoiZ2l0aGFpZ2FnZW9yZ2UxMkBnbWFpbC5jb20iLCJ1cm9sZSI6ImFkbWluIiwiaWF0IjoxNjg4MDI0Nzk0LCJleHAiOjE2ODgwNTM1OTR9.I6o7iQiOPQIWteK8oSvgytHNuXbRzzoLvLEzYVUpj-A
jcx

########
POST http://localhost:8080/tags
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI4YzEzMmM0ZS1iMjM4LTQ4MWMtOWViNS0yNmM4ZDU3OGQ3NTEiLCJ1bmFtZSI6IkpvaGhueSBEZWVwIiwidWVtYWlsIjoiZ2l0aGFpZ2FnZW9yZ2UxMkBnbWFpbC5jb20iLCJ1cm9sZSI6ImFkbWluIiwiaWF0IjoxNjg4MDI0Nzk0LCJleHAiOjE2ODgwNTM1OTR9.I6o7iQiOPQIWteK8oSvgytHNuXbRzzoLvLEzYVUpj-A


{

    "qid":"05d9fb08-c4b8-47a4-b27b-b0a2fbce7983",
    "tname": "make your tags now"
}

####
PUT http://localhost:8080/users/pwd/c114b9fa-0c1b-44c3-8811-2462f1158030 
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJjMTE0YjlmYS0wYzFiLTQ0YzMtODgxMS0yNDYyZjExNTgwMzAiLCJ1bmFtZSI6IlNlbmlvciBEZXYiLCJ1ZW1haWwiOiJzZW5pb3JkZXZAZ21haWwuY29tIiwidXJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg4MDQ1Nzc4LCJleHAiOjE2ODgwNzQ1Nzh9.YG-N4g84kb1XG6iKT2nle4gaOMAeJ44Z3Lowx609B90


{
    "oldpwd": "@Ji_tU33",
    "newpwd": "@Ji_tU33"
}