CREATE OR ALTER PROCEDURE getAnswerVotes
AS
BEGIN
	SELECT * FROM ANSWERVOTES
END


CREATE OR ALTER PROCEDURE getAnswerVotesbyAid(@aid VARCHAR(200))
AS
BEGIN
	SELECT * FROM ANSWERVOTES WHERE aid=@aid
END

CREATE OR ALTER PROCEDURE getAnswerVotesbyid(@avid VARCHAR(200))
AS
BEGIN
	SELECT * FROM ANSWERVOTES WHERE avid=@avid
END