
CREATE OR ALTER PROCEDURE getallComments
AS
BEGIN
	SELECT * FROM COMMENTS WHERE cisDeleted=0
END



CREATE OR ALTER PROCEDURE getCommentAnswers(@aid VARCHAR(200))
AS
BEGIN
	SELECT * FROM COMMENTS WHERE aid=@aid AND cisDeleted=0
END


CREATE OR ALTER PROCEDURE getCommentsById(@cid VARCHAR(200))
AS
BEGIN
	SELECT * FROM COMMENTS WHERE cid=@cid AND cisDeleted=0
END


CREATE OR ALTER PROCEDURE getallComments
AS
BEGIN
	SELECT * FROM COMMENTS WHERE cisDeleted = 0
END

exec getallComments