CREATE OR ALTER PROCEDURE postQuestionTags(
	@qid VARCHAR(200), @tid VARCHAR(200)
)
AS
BEGIN
	INSERT INTO QUESTAGS (qid, tid) VALUES(@qid,@tid)
END

CREATE OR ALTER PROCEDURE getQuestionTag
AS
BEGIN
	SELECT * FROM QUESTAGS
END

CREATE OR ALTER PROCEDURE getQuestionTagbyQid(@qid VARCHAR(200))
AS
BEGIN
	SELECT * FROM QUESTAGS WHERE qid=@qid
END