CREATE TABLE ANSWERS (
	aid VARCHAR(200) PRIMARY KEY NOT NULL,
	qid VARCHAR(200) NOT NULL,
	uid VARCHAR(200) NOT NULL,
	atitle VARCHAR(400) NOT NULL,
	abody TEXT,
	FOREIGN KEY (qid) REFERENCES [dbo].[QUESTIONS] (qid),
	FOREIGN KEY (uid) REFERENCES [dbo].[USERS] (uid)
)

ALTER TABLE ANSWERS 
ADD adateanswered DATE DEFAULT GETDATE()

ALTER TABLE ANSWERS 
ALTER COLUMN abody TEXT NOT NULL
ALTER TABLE ANSWERS
ADD aisDeleted INT DEFAULT 0 NOT NULL

ALTER TABLE ANSWERS
DROP COLUMN adateanswered
