CREATE TABLE ANSWERVOTES (
	aid VARCHAR(200) NOT NULL,
	uid VARCHAR(200) NOT NULL,
	aupvotes INT DEFAULT 0,
	adownvotes INT DEFAULT 0,
	apreffered INT DEFAULT 0,
	FOREIGN KEY (aid) REFERENCES [dbo].[ANSWERS] (aid),
	FOREIGN KEY (uid) REFERENCES [dbo].[USERS] (uid)
)
select * from ANSWERVOTES
delete  from ANSWERVOTES
ALTER TABLE ANSWERVOTES
ADD avid VARCHAR(200) PRIMARY KEY