CREATE TABLE COMMENTS 
(
	cid VARCHAR(200) PRIMARY KEY NOT NULL,
	uid VARCHAR(200) NOT NULL,
	qid VARCHAR(200) NOT NULL,
	aid VARCHAR(200) NOT NULL,
	FOREIGN KEY (uid) REFERENCES [dbo].[USERS] (uid),
	FOREIGN KEY (qid) REFERENCES [dbo].[QUESTIONS] (qid),
	FOREIGN KEY (aid) REFERENCES [dbo].[ANSWERS] (aid)
)
select * from COMMENTS
ALTER TABLE COMMENTS
ADD cisDeleted INT DEFAULT 0
DROP COLUMN cbody

ADD cbody TEXT NOT NULL