

CREATE TABLE QUESTIONS (
	qid VARCHAR(200) PRIMARY KEY NOT NULL,
	uid VARCHAR(200) NOT NULL,
	qtitle VARCHAR(400) NOT NULL,
	qbody TEXT,
	qdatecreated DATE,
	FOREIGN KEY (uid) REFERENCES [dbo].[USERS] (uid)
)

select * from QUESTIONS

ALTER TABLE QUESTIONS
ADD qisDeleted INT DEFAULT 0 NOT NULL

ALTER TABLE QUESTIONS 
DROP COLUMN qdatecreated

ALTER TABLE QUESTIONS 
ADD qdatecreated DATE DEFAULT GETDATE()