CREATE TABLE TAGS (
	tid VARCHAR(200) PRIMARY KEY NOT NULL,
	tname VARCHAR(150) NOT NULL
)



SELECT * FROM TAGS
ALTER TABLE TAGS
ADD qid VARCHAR(200) 

ALTER TABLE TAGS
ADD CONSTRAINT FK_TAG_QUESTION
FOREIGN KEY (qid) REFERENCES QUESTIONS (qid)