CREATE TABLE USERS (
	uid VARCHAR(200) PRIMARY KEY NOT NULL,
	uname VARCHAR(200) NOT NULL,
	uemail VARCHAR(150) NOT NULL,
	upassword VARCHAR(300) NOT NULL,
	urole VARCHAR(100) DEFAULT 'user',
	uprofPic NVARCHAR(250),
	uemailSent INT DEFAULT 0,
	uisDeleted INT DEFAULT 0,
)


ALTER TABLE USERS
ADD UNIQUE (uemail)